ENH: Intelligently detect the path to <...>/bin/postprocess_cppoutput.awk.
     No hardcoded path any more.

     Abort script if awk script is not found, don't simply crash. FEAT2BASEDIR
     can be absolute path again.

     This is a backport from FEAST.

git-svn-id: svn://doncamillo.mathematik.tu-dortmund.de/Featflow2@7917 4b12f95d-9313-0410-afc9-bd26427041f1

diff --git a/bin/f90cpp b/bin/f90cpp
--- a/bin/f90cpp
+++ b/bin/f90cpp
@@ -30,6 +30,20 @@ addcppflags=""
 STORAGEGETBASE_CALLS_TO_MACRO=0
 cppcmd="cpp " # previously: "cpp -CC "
 
+AWK_SCRIPT="`dirname $0`/postprocess_cppoutput.awk"
+if test ! -f ${AWK_SCRIPT}; then
+    if test -n "${FEAT2BASEDIR}"; then
+	AWK_SCRIPT=${FEAT2BASEDIR}/bin/postprocess_cppoutput.awk
+    fi
+    if test ! -f ${AWK_SCRIPT}; then
+	echo $0": The environment variable FEAT2BASEDIR is not set. It is one way of"
+	echo $0": locating \${FEAT2BASEDIR}/bin/postprocess_cppoutput.awk, a script"
+	echo $0": needed by this script. The default locate mechanism did not work"
+	echo $0": either. Aborting compilation..."
+	exit 1
+    fi
+fi
+
 # Loop through command line arguments and 
 # filter out the Fortran90 source file.
 while : true
@@ -286,8 +300,8 @@ fi
 # (particularly remove the absolute path to the source file as it likely
 #  blows the 132 character limit the Fortran 90/95 standard imposes)
 perl -pe "s/MYNEWLINE/\n/g; s%${objdir}/%%g; s|\. TRUE \.|.TRUE.|g; s|\. FALSE \.|.FALSE.|g; s|\/=%\/~|//|g; s|\/=%\*~|/*|g; s|\\\\=%/~~$|\\\\|; s/= >/=>/g;" < ${preprocessedfile}".$$" | \
-    awk -f ../../bin/postprocess_cppoutput.awk | \
-    sed 's/^\#/!\#/g;' > ${preprocessedfile}
+    awk -f ${AWK_SCRIPT} | \
+    sed 's/^\#/\!\#/g;' > ${preprocessedfile}
 
 # remove temporary files
 \rm ${preprocessedfile}".$$"
