ENH: Added support for application's extra source files.
     If an application requires extra source files which are not
     Fortran 90 files then these files can be passed to configure via
     the new parameter --srcextra_app. These files will be compiled by
     the Fortran, C, C++ or CUDA compiler depending on their suffix.

     In addition CUDA support for individual files passed to configure via
     the new parameter --srcextra_app has been added.

     This patch is largely based on code and suggestions provided by
     Sven Buijssen. So it is him who we owe this commit!

git-svn-id: svn://doncamillo.mathematik.tu-dortmund.de/Featflow2@8939 4b12f95d-9313-0410-afc9-bd26427041f1

diff --git a/Makefile.cpu.inc b/Makefile.cpu.inc
--- a/Makefile.cpu.inc
+++ b/Makefile.cpu.inc
@@ -2692,6 +2692,19 @@ endif
 endif
 
 
+##############################################################################
+# Add CUDA support
+##############################################################################
+HAS_CUDA10 := $(shell echo $(HAS_CUDA10) | tr '[a-z]' '[A-Z]')
+HAS_CUDA11 := $(shell echo $(HAS_CUDA11) | tr '[a-z]' '[A-Z]')
+HAS_CUDA12 := $(shell echo $(HAS_CUDA12) | tr '[a-z]' '[A-Z]')
+HAS_CUDA13 := $(shell echo $(HAS_CUDA13) | tr '[a-z]' '[A-Z]')
+HAS_CUDA20 := $(shell echo $(HAS_CUDA20) | tr '[a-z]' '[A-Z]')
+HAS_CUDA21 := $(shell echo $(HAS_CUDA21) | tr '[a-z]' '[A-Z]')
+ifneq (,$(findstring YES,$(HAS_CUDA10)$(HAS_CUDA11)$(HAS_CUDA12)$(HAS_CUDA13)$(HAS_CUDA20)$(HAS_CUDA21)))
+include $(TEMPLATESDIR)/nvcc-generic.mk
+endif
+
 
 ##############################################################################
 # Check for forced 32bit/64bit binary
@@ -2768,6 +2781,16 @@ endif
 	else \
 	    echo '  C++ compiler       : *** not set ! ***'; \
 	fi
+        # If cuda switch -DHAS_CUDAxx does occur in compiler flags,
+        # show CUDA compiler
+ifneq (,$(findstring YES,$(HAS_CUDA10)$(HAS_CUDA11)$(HAS_CUDA12)$(HAS_CUDA13)$(HAS_CUDA20)$(HAS_CUDA21)))
+	@if test -z "$(findstring exit 1, $(CUDA))"; then \
+	    echo '  CUDA compiler      :' $(shell (which 2>/dev/null $(CUDA) || \
+		echo "\*\*\* $(CUDA) not found ! \*\*\*")); \
+	else \
+	    echo '  CUDA compiler      : *** not set ! ***'; \
+	fi
+endif
 	@echo
 	@echo 'Linker to be used:'
 	@if test -z "$(findstring exit 1, $(LD))"; then \
@@ -2784,6 +2807,7 @@ endif
 	@echo '  CFLAGSF90    =' $(CFLAGSF90)
 	@echo '  CFLAGSC      =' $(CFLAGSC)
 	@echo '  CFLAGSCXX    =' $(CFLAGSCXX)
+	@echo '  CFLAGSCUDA   =' $(CFLAGSCUDA)
 	@echo '  LDFLAGS      =' $(LDFLAGS)
 	@echo '  APPONLYFLAGS =' $(APPONLYFLAGS)
 	@echo '  MODEXTENSION =' $(MODEXTENSION)
