ENH: Refuse to generate Makefile if object directory prefix is too long (attempt 3)
     Shave another character off the maximum allowed include directory length.

     Given that among the wide variety of compilers FeatFlow2 currently
     supports, PGI 7-13 are the only ones that complain about too long paths
     for include directories, altered the shell logic once more to only
     complain about too long path length if the build ID contains the "pgi"
     token.


git-svn-id: https://svn.mathematik.tu-dortmund.de:20443/svn/Featflow2@11985 4f116ff2-4e46-254c-a92c-0a7323bc4f3a

diff --git a/benchmark/apps_codire/configure b/benchmark/apps_codire/configure
--- a/benchmark/apps_codire/configure
+++ b/benchmark/apps_codire/configure
@@ -136,25 +136,29 @@ fi
 # used: If --objdir-prefix is overridden on the command line (when this
 # script is invoked), there is no point in checking the length.
 case "$@" in
-    *--objdir-prefix=*)
-	;;
-    *)
-	if [ "`echo ${OBJDIRPREFIX} | wc -c`" -gt "106" ]; then
-	   echo "$0: ERROR."
-	   echo "    Sorry, the object directory prefix, argument to command line option"
-           echo "    --objdir-prefix, is too long."
-	   echo "    The full object directory path - which will include also build ID info,"
-	   echo "    whether or not to use coprocessors and/or OpenMP and whether to do a debug"
-	   echo "    or release build - will most likely exceeds 162 characters. This may lead"
-	   echo "    to compilation errors, e.g. PGI 7-13 will not be able to locate include"
-	   echo "    files from a directory that long."
-	   echo "    Please abbreviate the object directory which is currently"
-	   echo "    set to:"
-	   echo "<"${OBJDIRPREFIX}">"
-	   echo
-	   echo "Application not configured."
-	   exit 1
-	fi
+    *--id=[A-Za-z0-9_-]*-pgi*)
+        case "$@" in
+	    *--objdir-prefix=*)
+	        ;;
+	    *)
+		if [ "`echo ${OBJDIRPREFIX} | wc -c`" -gt "105" ]; then
+		    echo "$0: ERROR."
+		    echo "    Sorry, the object directory prefix, argument to command line option"
+		    echo "    --objdir-prefix, is too long for the PGI compiler."
+		    echo "    The full object directory path - which will include also build ID info,"
+		    echo "    whether or not to use coprocessors and/or OpenMP and whether to do a debug"
+		    echo "    or release build - will most likely exceeds 162 characters. This will lead"
+		    echo "    to compilation errors with PGI 7-13 which will not be able to locate include"
+		    echo "    files from a directory that long."
+		    echo "    Please abbreviate the object directory which is currently"
+		    echo "    set to:"
+		    echo "<"${OBJDIRPREFIX}">"
+		    echo
+		    echo "Application not configured."
+		    exit 1
+		fi
+		;;
+	esac
 	;;
 esac
 
