BUG: Fixed regular expression when trying to match PGI compiler in build ID
     Such that the suggest reason why benchmark application is not found
     with PGI compiler, introduced in the previous revision, is actually
     shown.

git-svn-id: https://svn.mathematik.tu-dortmund.de:20443/svn/Featflow2@12249 4f116ff2-4e46-254c-a92c-0a7323bc4f3a

diff --git a/benchmark/include/runtests.template b/benchmark/include/runtests.template
--- a/benchmark/include/runtests.template
+++ b/benchmark/include/runtests.template
@@ -772,11 +772,11 @@ WARNING! For this application / test class there are no instructions
 	echo
 	echo "FEAT2 benchmark binary <${appname}> not found."
 	case ${BUILDID} in
-	    pc64-.*-linux-pgi*)
-		echo "(Could it be that the build system refused to compile the FEAT2 benchmark";
-		echo " binary <${appname}>, because the object directory prefix path exceeds 104";
-		echo " characters (which is a problem with the PGI compiler as it fails to locate";
-		echo " a header file if the absolute path to said file exceeds 200 characters)?";
+	    *-*-*-pgi*)
+		(echo "(Could it be that the build system refused to compile the FEAT2 benchmark";
+		 echo " binary <${appname}>, because the object directory prefix path exceeds 104";
+		 echo " characters (which is a problem with the PGI compiler as it fails to locate";
+		 echo " a header file if the absolute path to said file exceeds 200 characters)?";) 1>&2
 		;;
 	esac
 	echo "TEST FAILED"
